[[https://github.com/ROCKTAKEY/lsp-latex][https://img.shields.io/github/tag/ROCKTAKEY/lsp-latex.svg?style=flat-square]]
[[file:LICENSE][https://img.shields.io/github/license/ROCKTAKEY/lsp-latex.svg?style=flat-square]]
[[https://github.com/ROCKTAKEY/lsp-latex/actions][https://img.shields.io/github/workflow/status/ROCKTAKEY/lsp-latex/CI/master.svg?style=flat-square]]
[[https://melpa.org/#/lsp-latex][file:https://melpa.org/packages/lsp-latex-badge.svg]]
* lsp-mode client for LaTeX.
* How to Use?
  - First, you have to install ~texlab~.
    Please install this [[https://github.com/latex-lsp/texlab/releases][here]].
  - Next, you should make ~lsp-mode~ available. See [[https://github.com/emacs-lsp/lsp-mode][lsp-mode]].
  - Now, you can use Language Server Protocol (LSP) on (la)tex-mode or yatex-mode just to evaluate this:

#+BEGIN_SRC emacs-lisp -n
  (add-to-list 'load-path "/path/to/lsp-latex")
  (require 'lsp-latex)
  ;; "texlab" must be located at a directory contained in `exec-path'.
  ;; If you want to put "texlab" somewhere else,
  ;; you can specify the path to "texlab" as follows:
  ;; (setq lsp-latex-texlab-executable "/path/to/texlab")

  (with-eval-after-load "tex-mode"
   (add-hook 'tex-mode-hook 'lsp)
   (add-hook 'latex-mode-hook 'lsp))

  ;; For YaTeX
  (with-eval-after-load "yatex"
   (add-hook 'yatex-mode-hook 'lsp))
#+END_SRC
* Functions
** ~lsp-latex-build~
   Build .tex files with texlab.
   It use latexmk by default, so add .latexmkrc if you want to customize
   latex commands or options. You can change build command and option to other
   such as `make`, by changing ~lsp-latex-build-executable~ and
   ~lsp-latex-build-args~.

   This command build asynchronously by default, while it build synchronously
   with prefix argument(C-u).
** ~lsp-latex-forward-search~
   Move to current position on pdf viewer.
   To use, you should set ~lsp-latex-forward-search-executable~ and
   ~lsp-latex-forward-search-args~ according to your pdf viewer.
   See also [[https://texlab.netlify.app/docs/installation/previewing]].
   ~latex.forwardSearch.executable~ means ~lsp-latex-forward-search-executable~,
   and ~latex.forwardSearch.args~ means ~lsp-latex-forward-search-args~.
* Note
  In this package, you can use even texlab v0.4.2 or older, written with Java,
  though it is not recommended. If you want to use them, you can write like:
  #+BEGIN_SRC emacs-lisp -n
  ;; Path to Java executable. If it is added to environmental PATH,
  ;; you don't have to write this.
  (setq lsp-latex-java-executable "/path/to/java")

  ;; "texlab.jar" must be located at a directory contained in `exec-path'
  ;; "texlab" must be located at a directory contained in `exec-path'.
  (setq lsp-latex-texlab-jar-file 'search-from-exec-path)
  ;; If you want to put "texlab.jar" somewhere else,
  ;; you can specify the path to "texlab.jar" as follows:
  ;; (setq lsp-latex-texlab-jar-file "/path/to/texlab.jar")
  #+END_SRC
* License
  This package is licensed by GPLv3. See [[file:LICENSE][LICENSE]].
